apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configure-provider-deployment-role-binding
  namespace: crossplane-system
subjects:
- kind: ServiceAccount
  name: configure-provider-deployment-sa
  namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: configure-provider-deployment-role
  apiGroup: rbac.authorization.k8s.io

