kind: ConfigMap
apiVersion: v1
metadata:
  name: rhacm-aws-install-config-configmap
  namespace: aws-resources # Remember, this has to match the corresponding hyperscaler namespace name in the cluster-crud subdirectory defined within the namespaces directory of this repository.
data:
  baseDomain: onetouchprovisioning.com
  compute: |
    replicas=3
    architecture=amd64
    platform.aws.type=m5.xlarge
    platform.aws.rootVolume.iops=2000
    platform.aws.rootVolume.size=100
    platform.aws.rootVolume.type=io1
  controlPlane: |
    replicas=3
    architecture=amd64
    platform.aws.type=m5.xlarge
    platform.aws.rootVolume.iops=4000
    platform.aws.rootVolume.size=100
    platform.aws.rootVolume.type=io1
  klusterlet: |
    cloud=Amazon
    vendor=OpenShift
    applicationManager.enabled=true
    policyController.enabled=true
    searchCollector.enabled=true
    certPolicyController.enabled=true
    iamPolicyController.enabled=true
  managedCluster: |
    cloud=Amazon
    vendor=OpenShift
  versions: |
    4.9=img4.9.56-x86-64-appsub
    4.10=img4.10.53-x86-64-appsub
    4.11=img4.11.31-x86-64-appsub
    4.12=img4.12.7-multi-appsub
